// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRc7vfePmgCtqymLPJ3Gl7RD-Hk6BZAE',
    appId: '1:331677584932:android:bcb00f4e3a0dec6b3712b1',
    messagingSenderId: '331677584932',
    projectId: 'don-t4get2use',
    databaseURL: 'https://don-t4get2use-default-rtdb.firebaseio.com',
    storageBucket: 'don-t4get2use.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eoHo0cUup-vqv1cqRixm37aYi2DnQ4k',
    appId: '1:331677584932:ios:473d2c9f958031083712b1',
    messagingSenderId: '331677584932',
    projectId: 'don-t4get2use',
    databaseURL: 'https://don-t4get2use-default-rtdb.firebaseio.com',
    storageBucket: 'don-t4get2use.firebasestorage.app',
    iosBundleId: 'lab.p4c.dont4get2use2',
  );

}